### ISSUE TITLE
Not a pcap capture file (bad magic)

### ISSUE THREAD

**Issue by muhammadzulfanazhari** [ytisf/LookingGlass#1]
hi, 
I got error message like this
 Running in single file mode.
Traceback (most recent call last):
  File "looking_glass.py", line 677, in <module>
    main()
  File "looking_glass.py", line 643, in main
    _execution_wrapper(location)
  File "looking_glass.py", line 401, in _execution_wrapper
    pckts = load_pcap(file_name)  # Read packets from PCAP
  File "looking_glass.py", line 131, in load_pcap
    a = PcapReader(path_to_pcap)
  File "/home/zulfan/.local/lib/python2.7/site-packages/scapy/utils.py", line 628, in __init__
    RawPcapReader.__init__(self, filename)
  File "/home/zulfan/.local/lib/python2.7/site-packages/scapy/utils.py", line 552, in __init__
    raise Scapy_Exception("Not a pcap capture file (bad magic)")
scapy.error.Scapy_Exception: Not a pcap capture file (bad magic)

what's the problem?

**Comment by ytisf** [comment]
Hey, 
Seems like Scapy was not able to parse that PCAP files (maybe PCAPNG?). 
Pushing an update to give proper error message on screen.

**Comment by muhammadzulfanazhari** [comment]
it works now, but the csv file is empty

**Comment by ytisf** [comment]
Then it must have found no hits.  If the CSV is empty, it means none of the criteria for the search were met.

**Comment by muhammadzulfanazhari** [comment]
oh, I see. thank for your response
